name: La Fama Events
favicon: null
layout_spectrum: 0.99702
typography_spectrum: 0.3920370889827609
title: La Fama Events Seattle
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2cd17d'
    - '#c310d9'
    - '#f05663'
    - '#fefefe'
    - '#000000'
  brandStrength: 0.5
  lightness: 0.38239182624965906
  saturation: 0.49208916281349957
  rhythmicContrast: 0.32002059556543827
purpose: []
