name: La Fama Events
favicon: null
layout_spectrum: 0.48305
typography_spectrum: 0.74547
title: La Fama Events Seattle
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6fbf5'
    - '#000000'
    - '#f70001'
    - '#4b4d4a'
    - '#b5b7b4'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
